---
# hosts could have been "remote" or "all" as well

- hosts: all
  gather_facts: no
  connection: local
  tasks:
  - name: configure the login banner
    ios_banner:
      banner: login
      text: |
        ====================================================================
        WARNING: Suck it.
        ====================================================================
      state: present
  - name: configure MOTD
    ios_banner:
      banner: MOTD
      text: 'Chuck Norris says hi.'
      state: present
...
