---
# hosts could have been "remote" or "all" as well

- hosts: all
  gather_facts: no
  connection: local
  tasks:
  - name: configure the login banner
    ios_banner:
      banner: login
      text: |
        ====================================================================
        WARNING: This is the login banner.
         ====================================================================
      state: present
  - name: configure MOTD
    ios_banner:
      banner: motd
      text: 'Chuck Norris says hi.  FYI this is the MOTD'
      state: present
    - name: configure connection banner
      ios_banner:
      banner: connection
      text: 'Connection banner.'
      state: present
...
